# Generated by Django 3.0.8 on 2020-08-12 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='DNI',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='name',
            new_name='first_name',
        ),
    ]
