# Generated by Django 3.0.8 on 2020-08-12 20:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_auto_20200812_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='email',
            field=models.EmailField(default='none@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='loan',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('Other', 'Other')], default='Other', max_length=10),
        ),
        migrations.AddField(
            model_name='loan',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
